name: Deploy PiSAFE

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Generate SSL certificates securely
      - name: Generate SSL certificates
        run: |
          mkdir -p certs
          openssl req -x509 -newkey rsa:2048 -keyout certs/server.key -out certs/server.crt -days 365 -nodes \
            -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"

      # Step 5: Run Linting to Check Code Quality
      - name: Run Linting
        run: |
          pip install flake8
          flake8 .
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}

      # Step 6: Run Flask Application Tests (Optional: Add Your Test Scripts)
      - name: Run Flask Tests
        run: |
          python -m unittest discover -s tests
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FCM_SERVER_KEY: ${{ secrets.FCM_SERVER_KEY }}

      # Step 7: Deploy the Application (If Deployment Server is Configured)
      - name: Deploy Application
        run: |
          gunicorn --certfile certs/server.crt --keyfile certs/server.key -b 0.0.0.0:5000 flask_server:app
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FCM_SERVER_KEY: ${{ secrets.FCM_SERVER_KEY }}

      # Step 8: Save Logs and Artifacts for Debugging (Optional)
      - name: Upload Workflow Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: ./logs
