name: Deploy PiSafe

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Test application
      run: |
        python -m unittest discover -s tests

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H <your-pi-ip> >> ~/.ssh/known_hosts

    - name: Deploy to Raspberry Pi
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh pi@<your-pi-ip> 'cd /home/pi/PiSafe && git pull && gunicorn -w 4 -b 0.0.0.0:5000 eas_flask_server:app'
